# -*- coding: utf-8 -*-
"""chap4ex3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJyQWyCAg92u4DY3vpbbl_fbNKcsAhyJ
"""

alien_color = 'green'
if alien_color == 'green':
    print("You have earned 5 points!")
elif alien_color == 'yellow':
    print("You have earned 10 points!")
elif alien_color == 'red':
    print("You have earned 15 points!")

alien_color = 'yellow'
if alien_color == 'green':
    print("You have earned 5 points!")
elif alien_color == 'yellow':
    print("You have earned 10 points!")
elif alien_color == 'red':
    print("You have earned 15 points!")

alien_color = 'red'
if alien_color == 'green':
    print("You have earned 5 points!")
elif alien_color == 'yellow':
    print("You have earned 10 points!")
elif alien_color == 'red':
    print("You have earned 15 points!")
