# -*- coding: utf-8 -*-
"""chap4ex5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJyQWyCAg92u4DY3vpbbl_fbNKcsAhyJ
"""

favorite_fruits = ["orange", "mango", "watermelon"]
if 'orange' in favorite_fruits:
    print("You really like oranges!")
if 'mango' in favorite_fruits:
    print("You really like mangoes!")
if 'watermelon' in favorite_fruits:
    print("You really like watermelons!")
if 'avocado' in favorite_fruits:
    print("You really like avocados!")
if 'apple' in favorite_fruits:
    print("You really like apples!")
